spring:
  jackson:
    default-property-inclusion: NON_NULL
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/condominio
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  web:
    resources:
      add-mappings: true