spring:
  jackson:
    default-property-inclusion: NON_NULL
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demo_db;MODE=PostgreSQL
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /console
  flyway:
    enabled: true
    locations: classpath:/migrations
  sql:
    init:
      mode: always
  web:
    resources:
      add-mappings: true